server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_service
    username: root
    password: root123
  application:
      name: doctor_service

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


