server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_service
    username: root
    password: root123
  application:
    name: appointment_service
  main:
      allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/